import { CorrHeatmap } from "../ui/charts/CorrHeatmap";
import { FanChart } from "../ui/charts/FanChart";
import { HBarChart } from "../ui/charts/HBarChart";
import { fmtMoney, fmtMoneyFull, fmtNum, fmtPct, fmtSignedPct } from "../ui/format";
import { REPORT_CSS } from "./reportCss";
import type { ReportData } from "./summary";

export interface Narrative {
  title: string;
  sections: Array<{ heading: string; paragraphs: string[] }>;
  keyTakeaways: string[];
}

/** The narrative is untrusted LLM output — validate before rendering. */
export function validateNarrative(raw: unknown): Narrative {
  if (typeof raw !== "object" || raw === null) throw new Error("narrative is not an object");
  const obj = raw as Record<string, unknown>;
  if (!Array.isArray(obj.sections) || obj.sections.length === 0) {
    throw new Error("narrative has no sections");
  }
  const sections = obj.sections
    .filter((s): s is Record<string, unknown> => typeof s === "object" && s !== null)
    .map((s) => ({
      heading: typeof s.heading === "string" ? s.heading.slice(0, 120) : "Untitled section",
      paragraphs: Array.isArray(s.paragraphs)
        ? s.paragraphs.filter((p): p is string => typeof p === "string").slice(0, 8)
        : [],
    }))
    .filter((s) => s.paragraphs.length > 0)
    .slice(0, 10);
  if (sections.length === 0) throw new Error("narrative sections are empty");
  return {
    title: typeof obj.title === "string" && obj.title.trim() ? obj.title.slice(0, 140) : "Portfolio Review",
    sections,
    keyTakeaways: Array.isArray(obj.keyTakeaways)
      ? obj.keyTakeaways.filter((t): t is string => typeof t === "string").slice(0, 6)
      : [],
  };
}

const SHORT_DISCLAIMER =
  "AI-assisted report for information only — not financial advice. All figures were computed locally by the Portfolio Simulator from historical market data; the narrative was written by an AI model and may contain errors.";

function fullDisclaimer(model: string, generatedDate: string): string {
  return (
    `Generated on ${generatedDate}. All statistics were computed by the Portfolio Simulator's local analytics engine from historical market data; ` +
    `the narrative text was generated by the AI model "${model}" from those statistics and may contain errors or omissions. ` +
    "Nothing here is investment advice or a recommendation to buy or sell anything. Past performance and simulations do not predict future results. " +
    "Scenario figures marked as estimates use simplified factor and duration models."
  );
}

function ReportDoc({ data, narrative }: { data: ReportData; narrative: Narrative }) {
  const episodeBars = data.episodes.map(({ episode, result }) => ({
    label: episode.name.split("(")[0].trim().slice(0, 12),
    value: result.portfolioPnL,
    display: `${fmtMoney(result.portfolioPnL)} (${fmtSignedPct(result.portfolioReturnPct)})`,
  }));
  const speculativeBars = data.speculative.map(({ scenario, result }) => ({
    label: scenario.name.split("&")[0].trim().slice(0, 12),
    value: result.portfolioPnL,
    display: `${fmtMoney(result.portfolioPnL)} (${fmtSignedPct(result.portfolioReturnPct)})`,
  }));

  return (
    <>
      <h1>{narrative.title}</h1>
      <div className="meta">
        Generated {data.generatedDate} · market data as of {data.dataAsOf} · portfolio value {fmtMoneyFull(data.totalValue)}
      </div>
      <div className="banner">{SHORT_DISCLAIMER}</div>

      <section>
        <h2>Holdings</h2>
        <table className="data">
          <thead>
            <tr>
              <th>Symbol</th>
              <th>Name</th>
              <th className="num">Shares</th>
              <th className="num">Value</th>
              <th className="num">Weight</th>
            </tr>
          </thead>
          <tbody>
            {data.holdings.map((h) => (
              <tr key={h.symbol}>
                <td>{h.symbol}</td>
                <td>{h.name}</td>
                <td className="num">{h.shares.toLocaleString("en-US", { maximumFractionDigits: 4 })}</td>
                <td className="num">{fmtMoneyFull(h.value)}</td>
                <td className="num">{fmtPct(h.weight)}</td>
              </tr>
            ))}
            {data.cash > 0 && (
              <tr>
                <td>Cash</td>
                <td>US Dollars</td>
                <td className="num">—</td>
                <td className="num">{fmtMoneyFull(data.cash)}</td>
                <td className="num">{fmtPct(data.totalValue ? data.cash / data.totalValue : 0)}</td>
              </tr>
            )}
          </tbody>
        </table>
      </section>

      {data.risk && (
        <section>
          <h2>Risk statistics</h2>
          <table className="data">
            <tbody>
              <tr><td>Annualized volatility</td><td className="num">{fmtPct(data.risk.vol)}</td></tr>
              <tr><td>Sharpe ratio</td><td className="num">{fmtNum(data.risk.sharpe)}</td></tr>
              <tr><td>Maximum drawdown</td><td className="num">{fmtPct(data.risk.maxDD)}</td></tr>
              <tr><td>Monthly VaR (95%)</td><td className="num">{fmtPct(data.risk.var95)}</td></tr>
              <tr><td>Monthly CVaR (95%)</td><td className="num">{fmtPct(data.risk.cvar95)}</td></tr>
            </tbody>
          </table>
        </section>
      )}

      {narrative.sections.map((s) => (
        <section key={s.heading}>
          <h2>{s.heading}</h2>
          {s.paragraphs.map((p, i) => (
            <p key={i}>{p}</p>
          ))}
        </section>
      ))}

      {episodeBars.length > 0 && (
        <section>
          <h2>Historical stress tests (portfolio impact)</h2>
          <HBarChart data={episodeBars} />
        </section>
      )}

      {speculativeBars.length > 0 && (
        <section>
          <h2>Forward-looking scenarios (speculative)</h2>
          <HBarChart data={speculativeBars} />
          <p className="meta">
            What-if worlds built from authored category-level assumptions (shown in the app's Scenarios tab) — not
            predictions, and unlike the historical stress tests above, none of this has happened.
          </p>
        </section>
      )}

      {data.projection && (
        <section>
          <h2>20-year projection</h2>
          <FanChart result={data.projection} />
          <p className="meta">
            2,000 simulated paths, {data.projectionBasis}; no monthly contributions assumed. Figures are nominal.
          </p>
        </section>
      )}

      {data.correlation && (
        <section>
          <h2>Correlation between holdings</h2>
          <CorrHeatmap labels={data.correlation.labels} matrix={data.correlation.matrix} />
        </section>
      )}

      {narrative.keyTakeaways.length > 0 && (
        <section>
          <h2>Key takeaways</h2>
          <ul className="takeaways">
            {narrative.keyTakeaways.map((t) => (
              <li key={t}>{t}</li>
            ))}
          </ul>
        </section>
      )}
    </>
  );
}

/** Compose the fully self-contained report document. react-dom/server is
 * imported dynamically so it stays out of the main bundle. */
export async function renderReportHtml(
  data: ReportData,
  narrative: Narrative,
  model: string,
): Promise<string> {
  const { renderToStaticMarkup } = await import("react-dom/server");
  const body = renderToStaticMarkup(<ReportDoc data={data} narrative={narrative} />);
  const footer = renderToStaticMarkup(<footer>{fullDisclaimer(model, data.generatedDate)}</footer>);
  return (
    "<!doctype html>\n" +
    `<html lang="en"><head><meta charset="utf-8"/>` +
    `<meta name="viewport" content="width=device-width, initial-scale=1.0"/>` +
    `<meta name="color-scheme" content="light"/>` +
    `<title>${escapeHtml(narrative.title)}</title>` +
    `<style>${REPORT_CSS}</style>` +
    `</head><body>${body}${footer}</body></html>`
  );
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
